blank_issues_enabled: false
contact_links:
  - name: Fragen und Ideen / Questions and ideas
    url: https://github.com/kurim/ha-BerlinGreen/discussions
    about: Für Fragen und Ideen bitte die Diskussionen nutzen (falls aktiviert), Fehler als Issue melden.
